type Product @collection(name: "products") {
  name: String!
  description: String!
  price: Float!
  quantity: Int!
  image: String! # Image URL
  sexe: String!
  size: String!
  brand: String!
  etat: String!
  tags: [String!]!
  creation: Long # Timestamp as Int but was too big to fit in Int
}

type Customer @embedded {
  firstName: String!
  lastName: String!
  address: Address!
  telephone: String!
  email: String!
}

type Request @collection(name: "requests") {
  customer: Customer!
  address: Address!
  description: String!
}

type Order @collection(name: "orders") {
  customer: Customer!
  line: [ProductLine!]!
  creationDate: Time!
  shipAddress: Address!
}

type Address @embedded {
  street: String!
  city: String!
  country: String!
  zipCode: String!
}

type ProductLine @embedded {
  product: Product!
  quantity: Int!
  price: Float! # Total price
}

type Query {
  allProducts: [Product!]! @index(name: "all_products")
  allOrders: [Order!]! @index(name: "all_orders")
  allRequest: [Request!]! @index(name: "all_requests")
}