export default `-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1R3tazIvDwaMR4ZZ
Fw++Z9Kj35PC55o2IEgF95Q+n5agCgYIKoZIzj0DAQehRANCAAQm2ztKMPVcSGAf
oL/eylnVgji7B6/S7jw8RMtHOECYEuCypxNwJbQubrsSvhfDVvuRnpIJ9bNv1Mkz
l2gqfTxy
-----END PRIVATE KEY-----`